name: network_inflation
channels:
  - default
  - conda-forge
  - pytorch
dependencies:
  - python>=3.7
  - google-cloud-storage
  - jupyter
  - matplotlib
  - pytorch
  - torchdata
  - torchinfo
  - torchvision
  - tqdm