name: network_inflation
channels:
  - conda-forge
  - pytorch
dependencies:
  - huggingface_hub
  - ipywidgets
  - jpeg
  - jupyter
  - libpng
  - matplotlib
  - numpy
  - pytorch
  - scipy
  - torchdata 
  - torchinfo
  - torchvision
  - tqdm