name: network_inflation
channels:
  - default
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>=3.7
  - jupyter
  - matplotlib
  - pytorch
  - pytorch-cuda
  - torchdata
  - torchinfo
  - torchvision
  - tqdm