name: network_inflation
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.7
  - jupyter
  - matplotlib
  - pytorch::pytorch=1.13.1
  - pytorch::torchdata
  - conda-forge::torchinfo
  - pytorch::torchvision=0.14.1
  - tqdm