import argparse
import glob
from os import environ
from pathlib import Path
import shutil
import sys
import tarfile

from tqdm import tqdm

parser = argparse.ArgumentParser(prog="ResNet divergence script")
parser.add_argument(
    "imagenet_repo",
    type=Path,
    help="Huggingface imagenet repo path generated by `git clone https://huggingface.co/datasets/imagenet-1k`",
)
parser.add_argument(
    "--imagenet_path",
    default=environ.get("IMAGENET_PATH", "/mnt/imagenet/imagenet-1k"),
    type=Path,
)
args = parser.parse_args()


def get_files(split: str):
    files = [
        *glob.glob(f"{args.imagenet_repo}/data/{split}_images.tar.gz"),
        *glob.glob(f"{args.imagenet_repo}/data/{split}_images_[0-9].tar.gz"),
    ]
    files.sort()
    return files


def transform_name(name: str):
    dots = name.split(".")
    base, ext = ".".join(dots[:-1]), dots[-1]
    bars = base.split("_")
    name, label = f"{'_'.join(bars[:-1])}.{ext}", bars[-1]
    return name, label


# Setup output dir

args.imagenet_path.mkdir(parents=True, exist_ok=True)
for split in ["test", "train", "val"]:
    args.imagenet_path.joinpath(split).mkdir(exist_ok=True)

# Extract files

shutil.copy(
    args.imagenet_repo.joinpath("classes.py"), args.imagenet_path.joinpath("classes.py")
)

for split in ["train", "val"]:
    split_total = 0
    for filename in get_files(split):
        print(f"Reading `{filename}`")
        with tarfile.open(filename, "r:gz") as tar:
            for member in tqdm(tar.getmembers()):
                split_total += 1
                name, label = transform_name(member.name)
                label_dir = args.imagenet_path.joinpath(split, label)
                label_dir.mkdir(exist_ok=True)
                with tar.extractfile(member) as extract:
                    with label_dir.joinpath(name).open(mode="wb") as output:
                        output.write(extract.read())
    print(f"Total {split}: {split_total}")

test_total = 0
for filename in get_files("test"):
    print(f"Reading `{filename}`")
    with tarfile.open(filename, "r:gz") as tar:
        for member in tqdm(tar.getmembers()):
            test_total += 1
            with tar.extractfile(member) as extract:
                with args.imagenet_path.joinpath("test", name).open(
                    mode="wb"
                ) as output:
                    output.write(extract.read())
print(f"Total test: {test_total}")
